# Generated by Django 2.0.1 on 2018-03-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_auto_20180316_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_topic',
            field=models.TextField(blank=True),
        ),
    ]
